image: node:latest

build:
  type: build
  stage: build
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=clickclack-api --api-key=$HEROKU_API_KEY
  only:
    - master
  
test:
  stage: test
  script: echo "Running tests"
  script: npm run test
  
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rec-clickclack-api --api-key=$HEROKU_API_KEY
  only:
    - master


