image: node:latest

stages:
    - deploy to REC
    - test in REC
    - deploy to STAGING
    - test in STAGING
    - deploy PROD

build-job:
  stage: deploy to REC
  environment:
    name: REC
    url: https://rec-clickclack-api.herokuapp.com
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=clickclack-api --api-key=$HEROKU_API_KEY
  
test-unit-rec-job:
  stage: test in REC
  script: echo "Running unit tests in REC"
  
test-int-rec-job:
  stage: test in REC
  script: echo "Running integration tests in REC"
  
test-fun-rec-job:
  stage: test in REC
  script: echo "Running functional tests in REC"
  
test-e2e-rec-job:
  stage: test in REC
  script: echo "Running end to end tests in REC"

staging-job:
    stage: deploy to STAGING
    environment:
        name: STAGING
        url: https://staging-clickclack-api.herokuapp.com
    script: echo "staging"

test-unit-staging-job:
  stage: test in STAGING
  script: echo "Running unit tests in STAGING"
  
test-int-staging-job:
  stage: test in STAGING
  script: echo "Running integration tests in STAGING"
  
test-fun-staging-job:
  stage: test in STAGING
  script: echo "Running functional tests in STAGING"
  
test-e2e-staging-job:
  stage: test in STAGING
  script: echo "Running end to end tests in STAGING"
  
production-job:
  stage: deploy to PROD
  when: manual
  environment:
    name: PROD
    url: https://clickclack-api.herokuapp.com
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rec-clickclack-api --api-key=$HEROKU_API_KEY
