image: node:latest

stages:
    - deploy to REC
    - test in REC
    - deploy to PROD

build-job:
  stage: deploy to REC
  environment:
    name: REC
    url: https://rec-clickclack-api.herokuapp.com
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rec-clickclack-api --api-key=$HEROKU_API_KEY
  
trigger_build:
  stage: test in REC
  script:
    - "curl -X POST -F token=ebda0c52fa23f53e7afd0a9a2cb168 -F ref=clickclack-api -F ref=master https://gitlab.com/api/v4/projects/9571189/trigger/pipeline"

production-job:
  stage: deploy to PROD
  when: manual
  environment:
    name: PROD
    url: https://clickclack-api.herokuapp.com
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rec-clickclack-api --api-key=$HEROKU_API_KEY
