stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  environment:
    name: REC
    url: https://rec-clickclack-api.herokuapp.com
  script: echo "Building the app"
  script: git remote add rec https://git.heroku.com/rec-clickclack-api.git
  script: git push rec master

test:
  stage: test
  script: echo "Running tests"
  script: npm run test



deploy_staging:
  stage: deploy
  environment:
    name: PROD
    url: https://clickclack-api.herokuapp.com
  script: echo "Deploy to production server"
  script: git remote add prod https://git.heroku.com/clickclack-api.git
  script: git push prod master
