image: node:latest

stages:
    - build
    - test
    - staging
    - production

build-job:
  stage: build
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=clickclack-api --api-key=$HEROKU_API_KEY
  
test-job:
  stage: test
  script: echo "Running tests"
  script: npm run test
 
staging-job:
    stage: staging
    script: echo "staging"
  
production-job:
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rec-clickclack-api --api-key=$HEROKU_API_KEY